<?php
$PHORUM["DATA"]["LANG"]["registration_notification"]["Subject"] = "New user waits for registration verification!";
$PHORUM["DATA"]["LANG"]["registration_notification"]["Message"] = "\nA new user '%username%' (%useremail%) is waiting for registration approval on forum '%forumtitle%'.\n\nLog in at %login_url%\n\n\n--- this message is automatically generated by 'Phorum' ---";
?>
